language: python
dist: focal
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- '3.10'
install:
- pip install --upgrade pip pipenv virtualenv
- pip install -e .[dev]
- python -m build .
script:
- pylint version_checker
- pytest --cov=version_checker.utils tests/
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password: "pypi-AgEIcHlwaS5vcmcCJDljNzI0NzliLTJkMGEtNGI5My1iMWY2LTQyNjIzMzM3MmMwMgACKlszLCJjZmY3YjlmZi03MGZmLTQ5N2EtYTI4MC1jMjY0NTUzMjQ1MTAiXQAABiBgGtxxYhRnG5GLVveqSG7aRhhktkx0MS6TltmgODumnw"
  on:
    tags: true
