language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
# simultaneously verifies we can build the wheel & verify some targets
install:
  - pip install --upgrade pip pipenv virtualenv
  - pip install -e .[dev]
  - python -m build .
# command to run tests
script:
  - pylint version_checker
  - pytest --cov=version_checker.utils tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
