language: python
dist: focal
python:
- '3.7'
- '3.8'
- '3.9'
- '3.10'
install:
- pip install --upgrade pip pipenv virtualenv
- pip install -e .[dev]
- python -m build .
script:
- pylint version_checker
- pytest --cov=version_checker.utils tests/
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password:
    secure: "mi9oBV5jVJPDGOsl3ggaZxX1sggwLzUQeVnigjAYU/1YwYRetR7c6vrLpuHJ1Qozb8WZEdWKo6pt4hjCLV4W0XCxvMirlKbdczNGu/ItUz9dIAPiaPesAFORBS/KxGhZCPFeZ+CY/fInUQiU7cj+IX4wuXX6gkndZGCSQsumU+z/ggoxhopBPCMnfq8eY72lON7FuRKMiEt2KF5C9eZpwHl/lp2oyyxqjm2eILjkJIVqBIhBz5I3bKgCcgTbS5PGqDRfgHs4y6xQwa+DK9YeT3m9aLeRH5My0tWGPW4Yy9KflUk4kBI7RMXBHNQkIUNlzZzmiAQ+4vZBGAnDrio37PqiKyOUswaSVolBumo/14YQUut2Z+/TIjvFJcqycbkdegcx8LvEEU5PV7ws3G7UTaduUnnS9xRVmlLo/uTVMdXS/srPQ2iCpCGn8x9/jN52gHRKNb8zWi5gv6UGQ3eF37xHQgNTwXnFhf//+yQ8C+KZPfvHg5RIzPaOp2/RpsNNlApeTNPXUV3LexFJ8U22BBIPTieqh881RuOUgCxY3gNRDYyFcDBaK5GlpkKHRt48IRhuxp85/RcZwcUCi7GYiMNQGGa9l7+7mNacVOWNqxm9i/sElxcG4zVWuCqXQv6TUMVzV7TaMesDx7bk3J4HfoMvqJ4Ik/s4hPFgasVxIS0="
  on:
    tags: true
