language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -e .[dev]
# command to run tests
script:
  - pytest
  - pylint version-checker
  - pytest --cov=version_checker.utils tests/
# TODO add integration tests? artifact results?
