language: python
dist: focal
python:
- '3.7'
- '3.8'
- '3.9'
- '3.10'
install:
- pip install --upgrade pip pipenv virtualenv
- pip install -e .[dev]
- python -m build .
script:
- pylint version_checker
- pytest --cov=version_checker.utils tests/
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password:
    secure: MQsLe1R6j5xbwDp7/9gINaSCHVQLX2jrbG4GweT8bJLI8Ohj6EzPq197Ivyod6RD69ACsTtvJMgcsneLkDUfv59aAVqkocwgOyT7ivH+iuUff/k2+NOBv230AEjmaq+rcja41J4DJZbCxDxpn+uzzxXOP6jbCm6/E9xIBq1DCIWxUXgkUehhwNgy8/A1le1UeJ32yJ2/rPj5Td0lOuyVkwm2WmuFPFvDW0weU4IPHAOibLDz6hO4D3jGboDViY+X+MsttVcWqrUgi46hgib4nqoHYqZNryQVC9MZzL2q7nOF5uzOIIIfF4efegCnQoaXPnxsjm67BCEvSwmx1lB6TnHKxIQiyWt4jKWM3yTQHY6sKoHNrcTvlZIlzg5CRmUjTyUEmfCno/7mVbh74DM111rad5RYjfrUdmfh8dzYNvtMWg2iNhtM0mW+vNPh/0SrcjNwMSuBnDUwPVzrOHhofNd9k/oDE0sviRdH+MtXuKGupplgXEt29S+RvWd2Fynt1hk26vDhrvA1xq7vqC+MI2OE4c1dKp7l/2O8uHkdCMYos9gb0CzJO6eAmyk12rT6mGuwtZ2TfJm7a2QxlJDgs+NURscgoUehMR7mVLNQHcBFoPfsjCksfCSGx4r+qJ/drelg/3Go7JsK7aGd5eUv99axGLyFdUI0uxjmbXBzz0c=
  on:
    tags: true
